# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160511_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='black',
            new_name='pieces',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='red',
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(to='users.Game'),
        ),
    ]
