# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160511_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='games',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
