# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 01:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='eight',
        ),
        migrations.RemoveField(
            model_name='game',
            name='five',
        ),
        migrations.RemoveField(
            model_name='game',
            name='four',
        ),
        migrations.RemoveField(
            model_name='game',
            name='nine',
        ),
        migrations.RemoveField(
            model_name='game',
            name='one',
        ),
        migrations.RemoveField(
            model_name='game',
            name='seven',
        ),
        migrations.RemoveField(
            model_name='game',
            name='six',
        ),
        migrations.RemoveField(
            model_name='game',
            name='three',
        ),
        migrations.RemoveField(
            model_name='game',
            name='two',
        ),
        migrations.AddField(
            model_name='board',
            name='coordinates',
            field=models.ManyToManyField(to='games.Coordinate'),
        ),
        migrations.AddField(
            model_name='board',
            name='current_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='games.Board'),
        ),
    ]
