# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 02:18
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='coordinates',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=b'{"0": "empty", "1": "empty", "2": "empty", "3": "empty", "4": "empty", "5": "empty", "6": "empty", "7": "empty", "8": "empty"}', null=True),
        ),
    ]
